"""Read-only adapter exposing computed engine metrics to ReportAgent."""

from __future__ import annotations

import json
import os
import sys
from typing import Any, Dict, Optional

_SCRIPTS_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..', 'scripts'))
if _SCRIPTS_DIR not in sys.path:
    sys.path.insert(0, _SCRIPTS_DIR)

from engine.pack import load_pack  # noqa: E402
from engine.state import WorldState  # noqa: E402
from engine.metrics import MetricsEngine  # noqa: E402


class WorldStateReport:
    """Safely query metrics generated by a completed generic simulation."""

    def __init__(self, simulation_id: str):
        self.simulation_id = simulation_id
        self.sim_dir = os.path.abspath(os.path.join(
            os.path.dirname(__file__), '..', '..', 'uploads', 'simulations', simulation_id
        ))
        self._state: Optional[WorldState] = None
        self._metrics: Optional[MetricsEngine] = None
        self.domain = ""

        config_path = os.path.join(self.sim_dir, 'simulation_config.json')
        if not os.path.exists(config_path):
            return
        try:
            with open(config_path, 'r', encoding='utf-8') as f:
                config = json.load(f)
            pack_path = config.get('domain_pack_path') or os.path.join(self.sim_dir, 'domain_pack.json')
            self.domain = config.get('domain', '')
            pack = load_pack(pack_path)
            db_path = os.path.join(self.sim_dir, 'main_world.db')
            if os.path.exists(db_path):
                self._state = WorldState(db_path, allow_negative=pack.negative_resources)
                self._metrics = MetricsEngine(self._state, pack)
        except Exception:
            self._state = None
            self._metrics = None

    @property
    def available(self) -> bool:
        return self._metrics is not None

    def summary(self) -> Dict[str, Any]:
        if not self._state or not self._metrics:
            return {"available": False, "reason": "No completed generic world state is available."}
        return {
            "available": True,
            "domain": self.domain,
            "state": self._state.summary(),
            "metrics": self._metrics.available(),
        }

    def query(self, metric: str = "", round_range=None) -> Dict[str, Any]:
        if not self._state or not self._metrics:
            return {"available": False, "reason": "No completed generic world state is available."}
        if metric:
            return {"available": True, "domain": self.domain,
                    "result": self._metrics.compute(metric, round_range)}
        return {"available": True, "domain": self.domain,
                "result": self._metrics.compute_all()}

    def close(self) -> None:
        if self._state:
            self._state.close()
            self._state = None
            self._metrics = None


__all__ = ["WorldStateReport"]
